"(pymysql.err.IntegrityError) (1062, \"Duplicate entry '12' for key 'osobni_cislo'\") [SQL: 'INSERT INTO uzivatele (osobni_cislo, jmeno, _password, email, aktivni, `admin`, id_pobocka) VALUES (%(osobni_cislo)s, %(jmeno)s, %(_password)s, %(email)s, %(aktivni)s, %(admin)s, %(id_pobocka)s)'] [parameters: {'osobni_cislo': '12', 'jmeno': 'user', '_password': b'$2b$12$92QCaP38ADYgb6506hjFbetJKn8pnyo3DkdPlzO4ZPQ9nR2nadn8.', 'email': None, 'aktivni': 1, 'admin': 0, 'id_pobocka': '1'}] (Background on this error at: http://sqlalche.me/e/gkpj)"
